#!/bin/sh
# husky

# Created by Husky v4.3.8 (https://github.com/typicode/husky#readme)
#   At: 16/01/2021 09:26:44
#   From: undefined (https://github.com/typicode/husky#readme)

. "$(dirname "$0")/husky.sh"
